freebsd_instance:
  image: freebsd-12-0-release-amd64

freebsd_task:
  install_script:
    - pkg install -y cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  test_script:
    - cd build
    - ./test/memwalk/memwalk
    - ./test/mprotect/mprotect
    - ./test/mmap/mmap
    - ./test/regions/regions

osx_instance:
  image: mojave-base

osx_task:
  install_script:
    - brew install cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  test_script:
    - cd build
    - ./test/memwalk/memwalk
    - ./test/mprotect/mprotect
    - ./test/mmap/mmap
    - ./test/regions/regions
