freebsd_instance:
  image: freebsd-12-0-release-amd64

freebsd_build_task:
  install_script: pkg install -y cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./test/memwalk/memwalk
