freebsd_instance:
  image: freebsd-12-0-release-amd64

freebsd_pkg_task:
  script: pkg install -y cmake

configure_task:
  depends_on: freebsd_pkg_configure
  script:
    - mkdir build
    - cd build
    - cmake ..

build_task:
  depends_on: configure
  script:
    - cd build
    - make

test_task:
  depends_on: build
  script:
    - ./build/test/memwalk/memwalk
