freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  install_script:
    - pkg install -y cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  test_script:
    - cd build
    - ./test/memwalk/memwalk
    - ./test/mprotect/mprotect
    - ./test/mmap/mmap
    - ./test/regions/regions

osx_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  test_script:
    - cd build
    - ./test/memwalk/memwalk
    - ./test/mprotect/mprotect
    - ./test/mmap/mmap
    - ./test/regions/regions
